apache/maven-plugin-tools

maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/DefaultMojoAnnotationsScanner.java
pom.xml

The previous PR ignored JDK<9 builds and caused test failures on JDK9+. This PR should address these.

[MPLUGIN-335] - Fix build and tests

---

maven-plugin-plugin/src/it/annotation-with-inheritance-from-deps/pom.xml
maven-plugin-plugin/src/it/annotation-with-inheritance-reactor/pom.xml
maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/TestAnnotationsReader.java
maven-plugin-tools-api/src/test/java/org/apache/maven/tools/plugin/scanner/DefaultMojoScannerTest.java
maven-plugin-tools-api/src/test/java/org/apache/maven/tools/plugin/util/TestUtils.java
maven-plugin-tools-java/src/test/java/org/apache/maven/tools/plugin/extractor/javadoc/JavaMojoDescriptorExtractorTest.java
maven-script/maven-plugin-tools-ant/src/test/java/org/apache/maven/tools/plugin/extractor/ant/AntMojoDescriptorExtractorTest.java
maven-script/maven-plugin-tools-model/src/test/java/org/apache/maven/tools/plugin/extractor/model/PluginMetadataParserTest.java
maven-script/maven-script-ant/src/test/java/org/apache/maven/script/ant/AntMojoWrapperTest.java
pom.xml

And improve code use Java 7 syntax
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/apache/maven-plugin-tools/19)

[MPLUGIN-355] Upgrade to JUnit 4.12

---

pom.xml

@olamy also cleaned up the plugin description.

upgrade parent POM and other dependencies

---

pom.xml

deps: update plugins

---

maven-plugin-plugin/src/site/apt/examples/using-annotations.apt.vm

[MNGSITE-393] remove Maven 2 info

---

maven-plugin-tools-annotations/pom.xml

strict dependencies for maven-plugin-tools-annotations

---

maven-plugin-plugin/src/site/apt/index.apt

There were 4 goals listed, but it said "has six goals". Also the "help" goal was not listed.
Added the "help" goal and corrected the number from six to five.

(doc) added "help" goal; goal number corrected

---

maven-plugin-annotations/src/main/java/org/apache/maven/plugins/annotations/Parameter.java

eventually means finally, but what was rather meant is optionally

fix wording in javadoc

---

.gitignore
maven-plugin-plugin/src/main/java/org/apache/maven/artifact/repository/metadata/GroupRepositoryMetadata.java
maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/metadata/AddPluginArtifactMetadataMojo.java

https://issues.apache.org/jira/browse/MPLUGIN-384

[MPLUGIN-384] restore compatibility with Maven 3 ecosystem

---

maven-plugin-plugin/pom.xml
maven-plugin-tools-api/src/test/java/org/apache/maven/tools/plugin/util/stubs/MojoStub.java
maven-plugin-tools-generators/pom.xml
maven-plugin-tools-generators/src/test/java/org/apache/maven/tools/plugin/generator/stubs/MavenReportStub.java
pom.xml

- fix javadocs
- remove l10n-maven-plugin from reports
- use plugins version from parent

[MPLUGIN-397] Upgrade Parent to 36

---

maven-plugin-plugin/src/it/ant-reference-parameter/src/main/java/org/apache/maven/plugins/antWithRefs/ArtifactsTask.java
pom.xml

[MPLUGIN-389] Update level to Java 8

---

maven-plugin-plugin/src/it/annotation-with-inheritance-reactor/invoker.properties
maven-plugin-plugin/src/it/annotation-with-inheritance/invoker.properties
maven-plugin-plugin/src/it/ant-basic/invoker.properties
maven-plugin-plugin/src/it/ant-reference-parameter/invoker.properties
maven-plugin-plugin/src/it/ant-simple-usage/invoker.properties
maven-plugin-plugin/src/it/beanshell-simple/invoker.properties
maven-plugin-plugin/src/it/help-basic-jdk11/invoker.properties
maven-plugin-plugin/src/it/help-basic/invoker.properties
maven-plugin-plugin/src/it/ignore-plugin-class-realm/invoker.properties
maven-plugin-plugin/src/it/java-basic-annotations-jdk8/invoker.properties
maven-plugin-plugin/src/it/java-basic-annotations-jdkcurrent/invoker.properties
maven-plugin-plugin/src/it/java-basic-annotations/invoker.properties
maven-plugin-plugin/src/it/java-basic/invoker.properties
maven-plugin-plugin/src/it/mplugin-187/invoker.properties
maven-plugin-plugin/src/it/mplugin-223/invoker.properties
maven-plugin-plugin/src/it/mplugin-299_no-configuration/invoker.properties
maven-plugin-plugin/src/it/plugin-report-annotations/invoker.properties
maven-plugin-plugin/src/it/plugin-report/invoker.properties
maven-plugin-plugin/src/it/skip/invoker.properties

- skipTests is not needed, there are no unit test
- minimum Maven version is 3.2.5 - no need restrict to 3.0+

Cleanup IT tests - remove skipTests

---

maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/PluginReport.java

[MPLUGIN-402] optionally render <extensions>true</extensions> in usage

---

maven-plugin-plugin/src/it/plugin-info-jdk/pom.xml
maven-plugin-plugin/src/it/plugin-info-jdk/propertyRelease/pom.xml
maven-plugin-plugin/src/it/plugin-info-jdk/propertyRelease/src/main/resources/META-INF/maven/plugin.xml
maven-plugin-plugin/src/it/plugin-info-jdk/verify.groovy
maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/PluginReport.java

maven.compiler.release property

[MPLUGIN-404] Set JDK prerequisite preferably from release parameter or

---

maven-plugin-plugin/src/it/annotation-with-inheritance-from-deps/pom.xml
maven-plugin-plugin/src/it/annotation-with-inheritance/pom.xml
maven-plugin-plugin/src/it/help-basic-jdk11/pom.xml
maven-plugin-plugin/src/it/help-basic/pom.xml
maven-plugin-plugin/src/it/help-package/pom.xml
maven-plugin-plugin/src/it/java-basic-annotations-jdk8/pom.xml
maven-plugin-plugin/src/it/java-basic-annotations-jdkcurrent/pom.xml
maven-plugin-plugin/src/it/java-basic-annotations/pom.xml
maven-plugin-plugin/src/it/mplugin-299_no-configuration/pom.xml
maven-plugin-plugin/src/it/mplugin-324_javadoc/pom.xml
maven-plugin-plugin/src/it/mplugin-363_help-reproducible/pom.xml
maven-plugin-plugin/src/it/mplugin-372-annotation-with-inheritance-from-provided-deps/pom.xml
maven-plugin-plugin/src/it/mplugin-394_report-encoding/pom.xml
maven-plugin-plugin/src/it/packaging-jar/pom.xml
pom.xml

- use the same plexus-utils in tests

Bump plexus-utils to 3.4.2

---

src/site/xdoc/download.xml.vm

Discussed at https://github.com/apache/maven-ear-plugin/pull/78

Refresh download page

---

maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/converter/ConverterContext.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/converter/JavaClassConverterContext.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/converter/tag/LinkUtils.java
maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/converter/SimpleConverterContext.java
maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/converter/tag/LinkUtilsTest.java
maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/javadoc/JavadocLinkGenerator.java
maven-plugin-tools-api/src/test/java/org/apache/maven/tools/plugin/javadoc/JavadocLinkGeneratorTest.java
maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginDescriptorFilesGenerator.java

[MPLUGIN-429] Don't emit warning for missing javadoc URI if no javadoc

---

maven-plugin-plugin/pom.xml
maven-plugin-report-plugin/pom.xml
maven-plugin-tools-generators/pom.xml
maven-script/maven-script-ant/pom.xml
pom.xml

- excludes in one place
- exclude plexus-container-default
- exclude plexus-component-api

[MPLUGIN-434] Improve dependency management

---

maven-plugin-plugin/src/it/java-basic-annotations/verify.groovy
maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/DescriptorGeneratorMojo.java
maven-plugin-report-plugin/src/it/plugin-info-jdk-default-version/pom.xml
maven-plugin-report-plugin/src/it/plugin-report/pom.xml
maven-plugin-report-plugin/src/it/settings.xml
maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginReport.java
maven-plugin-report-plugin/src/main/java/org/apache/maven/plugins/plugin/descriptor/EnhancedPluginDescriptorBuilder.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/DefaultMojoAnnotationsScanner.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/MojoAnnotatedClass.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/MojoAnnotationsScannerRequest.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoClassVisitor.java
maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/ClassVersionComparatorTest.java
maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/DefaultPluginToolsRequest.java
maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/ExtendedMojoDescriptor.java
maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/ExtendedPluginDescriptor.java
maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/PluginToolsRequest.java
maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/extractor/MojoDescriptorExtractor.java
maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginDescriptorFilesGenerator.java
pom.xml

[MPLUGIN-425] Add required Java and Maven version to the generated

---

maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/extractor/AbstractScriptedMojoDescriptorExtractor.java
maven-plugin-tools-java/src/site/apt/index.apt
maven-script/maven-plugin-tools-ant/src/site/apt/index.apt
maven-script/maven-plugin-tools-beanshell/src/site/apt/index.apt
maven-script/pom.xml

maven-plugin-tools-annotations

[MPLUGIN-440] Clarify deprecation of all extractors but the

---

maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractorTest.java
maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/converter/JavaClassConverterContextTest.java
maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/javadoc/JavadocSite.java
maven-plugin-tools-api/src/test/java/org/apache/maven/tools/plugin/javadoc/JavadocLinkGeneratorTest.java
maven-plugin-tools-api/src/test/java/org/apache/maven/tools/plugin/javadoc/JavadocSiteIT.java
maven-plugin-tools-api/src/test/java/org/apache/maven/tools/plugin/javadoc/JavadocSiteTest.java

[MPLUGIN-444] JavadocLinkGenerator.createLink: Support nested binary

---

maven-plugin-tools-generators/pom.xml
pom.xml

This reverts commit df4b8fdaf719daed8b060ee161cd60f49761783c.

Revert "Bump plexus-velocity from 1.2 to 2.0 and velocity from 1.7 to 2.3 (#195)"

---

maven-plugin-report-plugin/src/it/mplugin-319_report-since/verify.groovy
maven-plugin-tools-generators/src/main/resources/pluginxdoc.properties
maven-plugin-tools-generators/src/test/resources/expected-testGoal-mojo.xml

[MPLUGIN-477] Don't add a stray period

---

maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/datamodel/ParameterAnnotationContent.java
maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoClassVisitor.java
maven-plugin-tools-java/src/main/java/org/apache/maven/tools/plugin/extractor/javadoc/JavaJavadocMojoDescriptorExtractor.java
maven-plugin-tools-java/src/test/java/org/apache/maven/tools/plugin/extractor/javadoc/JavaMojoDescriptorExtractorTest.java
maven-script/maven-script-ant/src/main/java/org/apache/maven/script/ant/AntPropertyHelper.java

@elharo since there's a long tail of projects that can still pick up diamond operators, I've started to combine those with the low volume simplify conditional expression. 
- https://issues.apache.org/jira/browse/MNG-6847
- https://issues.apache.org/jira/browse/MNG-7416
Figured that'd strike the right balance between still delivering value, while also minimizing PRs and reviews.
Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/SEvWu02zw?organizationId=QXBhY2hlIE1hdmVu

[MNG-7416] Simplify Boolean expressions and returns

---

maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginOverviewRenderer.java

As with other renderers move sections to specialized section rendering methods.

[MPLUGIN-498] Move section rendering to separate methods

---

maven-plugin-plugin/src/site/apt/examples/using-annotations.apt.vm

Remove decade+ old content

---

maven-plugin-annotations/pom.xml
maven-plugin-plugin/pom.xml
maven-plugin-report-plugin/pom.xml
maven-plugin-tools-annotations/pom.xml
maven-plugin-tools-api/pom.xml
maven-plugin-tools-generators/pom.xml
maven-plugin-tools-java/pom.xml
maven-script/maven-plugin-tools-ant/pom.xml
maven-script/maven-plugin-tools-beanshell/pom.xml
maven-script/maven-plugin-tools-model/pom.xml
maven-script/maven-script-ant/pom.xml
maven-script/maven-script-beanshell/pom.xml
maven-script/pom.xml
pom.xml

Bumping version before #310 can be merged.
https://github.com/apache/maven-plugin-tools/pull/310#discussion_r1695757092

Bump next version to 3.14.0-SNAPSHOT

---

maven-plugin-report-plugin/src/it/fix-maven-since-3.x/pom.xml
maven-plugin-report-plugin/src/it/mplugin-191/pom.xml
maven-plugin-report-plugin/src/it/mplugin-319_report-since/pom.xml
maven-plugin-report-plugin/src/it/mplugin-394_report-encoding/pom.xml
maven-plugin-report-plugin/src/it/plugin-info-jdk-default-version/pom.xml
maven-plugin-report-plugin/src/it/plugin-info-jdk/pom.xml
maven-plugin-report-plugin/src/it/plugin-no-fork-report/invoker.properties
maven-plugin-report-plugin/src/it/plugin-no-fork-report/pom.xml
maven-plugin-report-plugin/src/it/plugin-no-fork-report/src/main/java/org/DummyReport.java
maven-plugin-report-plugin/src/it/plugin-no-fork-report/src/main/java/org/MyMojo.java
maven-plugin-report-plugin/src/it/plugin-no-fork-report/verify.groovy
maven-plugin-report-plugin/src/it/plugin-report-annotations/pom.xml
maven-plugin-report-plugin/src/it/plugin-report-detect-requirements-history/pom.xml
maven-plugin-report-plugin/src/it/plugin-report-requirements-history/pom.xml
maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/pom.xml
maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginNoForkReport.java
maven-plugin-report-plugin/src/site/apt/examples/generate-report.apt.vm
maven-plugin-report-plugin/src/site/apt/index.apt
pom.xml

Add non-forking plugin report goal
https://issues.apache.org/jira/browse/MPLUGIN-529

[MPLUGIN-529] Add non-forking plugin report goal

---

maven-plugin-annotations/src/main/java/org/apache/maven/plugins/annotations/Component.java

Recommend using JSR 330 annotations instead

[MPLUGIN-530] Deprecate o.a.m.plugins.annotations.Component

---

maven-plugin-report-plugin/pom.xml
maven-plugin-report-plugin/src/it/plugin-report-annotations/src/main/java/org/DummyReport.java
maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/pom.xml
maven-plugin-report-plugin/src/it/plugin-report/pom.xml
maven-plugin-report-plugin/src/it/plugin-report/src/main/java/org/DummyReport.java
maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/GoalRenderer.java
maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginOverviewRenderer.java
maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginReport.java
maven-plugin-tools-generators/pom.xml
maven-plugin-tools-generators/src/test/resources/expected-testGoal-mojo.xml
pom.xml

[MPLUGIN-501] Upgrade to Doxia 2.0.0 Milestone Stack (Maven 3.x)

---

.github/workflows/maven-verify.yml
maven-plugin-plugin/src/it/v4api-3x/verify.groovy
maven-plugin-plugin/src/it/v4api-4x/verify.groovy
pom.xml

No other change is needed for building this repository.

[MPLUGIN-537] Set the core Maven dependency to 4.0.0-beta4

---

maven-plugin-report-plugin/pom.xml
pom.xml

[MPLUGIN-538] Upgrade to Doxia 2.0.0 GA Stack

---

maven-plugin-plugin/pom.xml
maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/AbstractGeneratorMojo.java
maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/DescriptorGeneratorMojo.java
maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/HelpGeneratorMojo.java
maven-plugin-plugin/src/test/java/org/apache/maven/plugin/plugin/HelpGeneratorMojoTest.java

This one's going to be long and involved across multiple submodules so let's take it one piece at a time.

Begin converting this plugin to Guice constructor injection

---

maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginNoForkReport.java
maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginReport.java
maven-plugin-report-plugin/src/main/resources/plugin-report.properties
maven-plugin-report-plugin/src/main/resources/plugin-report_de.properties

[MPLUGIN-541] Rename report from "Plugin Documentation" to "Plugin

---

maven-plugin-plugin/src/it/v4api-3x/verify.groovy
maven-plugin-plugin/src/it/v4api-4x/verify.groovy
pom.xml

This commit only changes the version number. There is apparently no other change needed.

Upgrade Maven 4 dependency from "4.0.0-beta-4" to "4.0.0-rc-3"

---

pom.xml

Reverts apache/maven-plugin-tools#326

Revert "Bump slf4jVersion from 1.7.36 to 2.0.0"

---

.github/ISSUE_TEMPLATE/BUG.yml
.github/ISSUE_TEMPLATE/FEATURE.yml
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md
README.md
pom.xml

* Release and Milestone already there

Github Issues

---

maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
pom.xml

Following this checklist to help us incorporate your
contribution quickly and easily:
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

JDK 25 build fix

---

maven-plugin-plugin/src/main/filtered-resources/META-INF/plexus/components.xml

Plugin versions are defined in parent pom
we cen use it.
---
Following this checklist to help us incorporate your
contribution quickly and easily:
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

Use properties for versions in components.xml
