- pom.xml
The ALPHA dependency causes problems to projects using Enforcer rules, see https://github.com/jenkinsci/jacoco-plugin/pull/92#issuecomment-349457441
> upgrade to ASM 6.1.1

- maven-plugin-tools-generators/src/main/resources/help-class-source.vm
> Add missing @Override and make methods static

- maven-plugin-plugin/pom.xml
- maven-plugin-plugin/src/it/mplugin-382-exclude-provided-dependency/invoker.properties
- maven-plugin-plugin/src/it/mplugin-382-exclude-provided-dependency/pom.xml
- maven-plugin-plugin/src/it/mplugin-382-exclude-provided-dependency/src/main/java/org/apache/maven/plugin/coreit/FirstMojo.java
- maven-plugin-plugin/src/it/mplugin-382-exclude-provided-dependency/verify.groovy
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/GeneratorUtils.java
- maven-plugin-tools-generators/src/test/java/org/apache/maven/tools/plugin/generator/GeneratorUtilsTest.java
`plugin.xml` descriptor - should only contain dependencies in compile scope
> [MPLUGIN-382] exclude dependency in provided scope from plugin descriptor

- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/AbstractGeneratorMojo.java
and craft strings along with OS native line ending just
manually. String.format w/o any param looks very
awkward.
> Get rid of String.format use

- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/AbstractGeneratorMojo.java
Commit 95f76d2b303c15de01bbb29e3d1a16db4595e44c missed
this one. Funnily, that commit got rid of use of
String.format and `%n`s, while here we have `\n`s.
> Fix this logging as well

- maven-plugin-plugin/src/site/apt/examples/using-annotations.apt.vm
Since maven-plugin-plugin require Maven 3.2.5 no additional configuration is needed.
> (doc) Simplify documentation

- maven-plugin-plugin/src/it/mplugin-370-maven-deps-scope-bad/pom.xml
- maven-plugin-plugin/src/it/mplugin-370-maven-deps-scope-bad/verify.groovy
- maven-plugin-plugin/src/it/mplugin-370-maven-deps-scope-good/pom.xml
- maven-plugin-plugin/src/it/mplugin-370-maven-deps-scope-good/verify.groovy
- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/AbstractGeneratorMojo.java
Those are not Maven Core components, they are merely in
wrong groupId. Extended ITs to use maven-jxr as well.
> [MPLUGIN-386] Exclude maven-archiver and maven-jxr from warning

- maven-plugin-plugin/src/it/mplugin-394_report-encoding/invoker.properties
- maven-plugin-plugin/src/it/mplugin-394_report-encoding/pom.xml
- maven-plugin-plugin/src/it/mplugin-394_report-encoding/src/main/java/test/MyMojo.java
- maven-plugin-plugin/src/it/mplugin-394_report-encoding/verify.groovy
- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/PluginReport.java
PluginReport didn't specify an encoding while reading the
Plugin-Descriptor. This causes the fallback to the plattform encoding
and ignores the (user specified) input encoding.
This commits adds an integration test to reproduce the error and fixes
it by using the input encoding for the creation of the used Reader.
The integration tests forces the plattform encoding to CP1252 (Western
European charset used in Windows) while the source (input) and output
encoding is UTF-8.
The source file contains non-ASCII characters which have a different
representation in both encodings.
> [MPLUGIN-394] Respect input encoding

- maven-plugin-tools-annotations/pom.xml
- maven-script/maven-script-ant/pom.xml
- pom.xml
- plexus-archiver from 3.6.0 to 4.2.7
- assertj-core from 2.9.1 to 3.22.0
- antVersion from 1.9.16 to 1.10.12
> [MPLUGIN-399] Upgrade project dependencies after JDK 1.8

- maven-plugin-plugin/src/it/annotation-with-inheritance-from-deps/pom.xml
- maven-plugin-plugin/src/it/annotation-with-inheritance-from-deps/src/main/java/org/apache/maven/plugin/coreit/FirstMojo.java
- maven-plugin-plugin/src/it/annotation-with-inheritance-from-deps/verify.groovy
- maven-plugin-plugin/src/it/annotation-with-inheritance-reactor/module-abstract-mojo/src/main/java/org/apache/maven/plugins/AbstractFirstMojo.java
- maven-plugin-plugin/src/it/annotation-with-inheritance-reactor/module-mojo/src/main/java/org/apache/maven/plugin/coreit/FirstMojo.java
- maven-plugin-plugin/src/it/annotation-with-inheritance-reactor/pom.xml
- maven-plugin-plugin/src/it/annotation-with-inheritance-reactor/verify.groovy
- maven-plugin-plugin/src/it/annotation-with-inheritance/pom.xml
- maven-plugin-plugin/src/it/annotation-with-inheritance/src/main/java/org/apache/maven/plugin/coreit/AbstractFirstMojo.java
- maven-plugin-plugin/src/it/annotation-with-inheritance/src/main/java/org/apache/maven/plugin/coreit/AbstractFooMojo.java
- maven-plugin-plugin/src/it/annotation-with-inheritance/src/main/java/org/apache/maven/plugin/coreit/FirstMojo.java
- maven-plugin-plugin/src/it/annotation-with-inheritance/src/main/java/org/apache/maven/plugin/coreit/ThirdMojo.java
- maven-plugin-plugin/src/it/annotation-with-inheritance/verify.groovy
- maven-plugin-plugin/src/it/mplugin-372-annotation-with-inheritance-from-provided-deps/pom.xml
- maven-plugin-plugin/src/it/mplugin-372-annotation-with-inheritance-from-provided-deps/src/main/java/org/apache/maven/plugin/coreit/FirstMojo.java
- maven-plugin-tools-annotations/pom.xml
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/FooMojo.java
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/TestAnnotationsReader.java
External dependency like plexus-compiler-manager no need to be used in tests.
The most of it tests used very old version of it.
> [MPLUGIN-411] Get rid of plexus-compiler-manager from tests

- maven-plugin-annotations/src/main/java/org/apache/maven/plugins/annotations/Parameter.java
- maven-plugin-plugin/pom.xml
- maven-plugin-plugin/src/it/annotation-with-inheritance-from-deps/verify.groovy
- maven-plugin-plugin/src/site/apt/examples/using-annotations.apt.vm
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/DefaultMojoAnnotationsScanner.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/MojoAnnotationsScanner.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoAnnotationVisitor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoClassVisitor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoMethodVisitor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoParameterVisitor.java
- maven-plugin-tools-annotations/src/site/apt/index.apt
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/FooMojo.java
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/TestAnnotationsReader.java
- new implementation
- remove some of unused or unneeded methods
> [MPLUGIN-419] Allow `@Parameter` on setters methods

- maven-plugin-tools-annotations/pom.xml
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/datamodel/ParameterAnnotationContent.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/DefaultMojoAnnotationsScanner.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoClassVisitor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoFieldVisitor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoMethodVisitor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoParameterVisitor.java
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/ParametersWithGenericsMojo.java
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/TestAnnotationsReader.java
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/DefaultMojoAnnotationsScannerTest.java
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginDescriptorFilesGenerator.java
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginXdocGenerator.java
- maven-plugin-tools-generators/src/test/java/org/apache/maven/tools/plugin/generator/PluginDescriptorFilesGeneratorTest.java
- maven-plugin-tools-generators/src/test/java/org/apache/maven/tools/plugin/generator/PluginXdocGeneratorTest.java
- pom.xml
> [MPLUGIN-427] Expose generics information of parameter types in report

- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/report_old/PluginReport.java
- maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/invoker.properties
- maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/pom.xml
- maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/src/main/java/org/MyMojo.java
- maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/src/main/java/org/SimpleBean.java
- maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/src/main/java/org/internal/PrivateBean.java
- maven-plugin-report-plugin/src/it/plugin-report-with-javadoc-links/verify.groovy
- maven-plugin-report-plugin/src/main/java/org/apache/maven/plugin/plugin/report/PluginReport.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/javadoc/JavadocLinkGenerator.java
- maven-plugin-tools-generators/pom.xml
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginXdocGenerator.java
- maven-plugin-tools-generators/src/test/java/org/apache/maven/tools/plugin/generator/PluginXdocGeneratorTest.java
Also validate internal links to javadocs in mojo/parameter description and deprecated
> [MPLUGIN-433] Allow to disable link validation

- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/converter/JavaClassConverterContext.java
When a mojo inherits from a mojo in a different project, the plugin descriptor generation fails.
Another problem is when the source artifact is being built in the same reactor, I had a case where the resolved artifacts file was pointing to a directory.
> [MPLUGIN-437] Fixes to the plugin descriptor generation

- maven-plugin-plugin/src/it/java-basic-annotations/verify.groovy
- maven-plugin-plugin/src/it/v4api/verify.groovy
- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/DescriptorGeneratorMojo.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/PluginToolsRequest.java
java version (derived from class version)
> [MPLUGIN-425] Generate version ranges for automatically detected minimal

- maven-plugin-plugin/src/it/java-basic-annotations/verify.groovy
- maven-plugin-plugin/src/it/v4api/verify.groovy
- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/DescriptorGeneratorMojo.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/PluginToolsRequest.java
Generate simple version constraints automatically
Fix Javadoc
> [MNG-7611] Change semantics of plugin descriptor's "requiredJavaVersion"

- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/DescriptorGeneratorMojo.java
Should be logged at WARN level, and not ERROR level. When Mojo logs ERROR, it is expected that it fails the build. And this also confuses the Verifier.
---
https://issues.apache.org/jira/browse/MPLUGIN-452
> [MPLUGIN-452] Maven scope and module name logs at wrong level

- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/report_old/PluginReport.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/visitors/MojoClassVisitor.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/DefaultPluginToolsRequest.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/extractor/AbstractScriptedMojoDescriptorExtractor.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/javadoc/JavadocReference.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/scanner/DefaultMojoScanner.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/util/PluginUtils.java
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/GeneratorUtils.java
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginDescriptorFilesGenerator.java
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginHelpGenerator.java
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginXdocGenerator.java
- maven-plugin-tools-java/src/main/java/org/apache/maven/tools/plugin/extractor/javadoc/JavaJavadocMojoDescriptorExtractor.java
- maven-script/maven-plugin-tools-ant/src/main/java/org/apache/maven/tools/plugin/extractor/ant/AntMojoDescriptorExtractor.java
- maven-script/maven-plugin-tools-model/src/main/java/org/apache/maven/tools/plugin/extractor/model/PluginMetadataParser.java
Continuation of https://issues.apache.org/jira/browse/MNG-6825
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
Review requested of @elharo
> [MNG-6829] Replace any StringUtils#isEmpty(String) and #isNotEmpty(String)

- maven-plugin-tools-annotations/src/site/apt/index.apt
clarify something which precise scope was unclear until now (at least to me)
=> update https://maven.apache.org/plugin-tools/maven-plugin-tools-annotations/
> [MNG-5695] document Maven 3.2.5+ scoped components usage

- maven-plugin-plugin/pom.xml
- maven-plugin-plugin/src/it/java-basic-annotations/verify.groovy
- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/DescriptorGeneratorMojo.java
- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/metadata/AddPluginArtifactMetadataMojo.java
- maven-plugin-plugin/src/main/java/org/apache/maven/plugin/plugin/metadata/LegacySupport.java
- maven-plugin-report-plugin/pom.xml
- maven-plugin-report-plugin/src/it/plugin-report-annotations/verify.groovy
- maven-plugin-report-plugin/src/it/plugin-report/verify.groovy
- pom.xml
Update parent POM to 42, up prerequisite to 3.6.3. As parent 42 removes implicit (sisu) indexing, added explicitly indexing to all modules, as I think they all need it (may be wrong here).
The Mojo `AddPluginArtifactMetadataMojo` pulls in classes that have transitive (classes) coming from maven-compat. In fact, this mojo is not required at all since Maven 3.9.0 as resolver handles all transparently.
---
https://issues.apache.org/jira/browse/MPLUGIN-519
https://issues.apache.org/jira/browse/MPLUGIN-520
> [MPLUGIN-519][MPLUGIN-520] Parent POM 42, prerequisite of 3.6.3, get rid of maven-compat

- maven-plugin-plugin/pom.xml
- maven-plugin-report-plugin/pom.xml
- maven-plugin-tools-annotations/pom.xml
- maven-plugin-tools-api/pom.xml
- maven-plugin-tools-generators/pom.xml
- maven-plugin-tools-java/pom.xml
- pom.xml
> [MPLUGIN-526] Clean up dependencies reported by dependencies:analyze

- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java
- maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/DefaultMojoAnnotationsScanner.java
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractorTest.java
- maven-plugin-tools-annotations/src/test/java/org/apache/maven/tools/plugin/extractor/annotations/scanner/DefaultMojoAnnotationsScannerTest.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/extractor/AbstractScriptedMojoDescriptorExtractor.java
- maven-plugin-tools-api/src/main/java/org/apache/maven/tools/plugin/scanner/DefaultMojoScanner.java
- maven-plugin-tools-generators/src/main/java/org/apache/maven/tools/plugin/generator/PluginHelpGenerator.java
As seen on https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=181305684#MavenEcosystemCleanup-DropPlexusContainerforJSR-330+SisuGuiceextension
- Leverages https://github.com/openrewrite/rewrite-apache/pull/41
I have another two lined up for apache/maven and apache/maven-archetype that I'll verify first.
@elharo if you wouldn't mind, could you look this over?
Use this link to re-run the recipe: https://app.moderne.io/builder/P4zH7djn6?organizationId=QXBhY2hlIE1hdmVu
> refactor: Replace Plexus AbstractLogEnabled with SLF4J

- pom.xml
This fixes parsing of annotations leveraging textblocks (https://github.com/paul-hammant/qdox/issues/124)
> [MPLUGIN-542] Update QDox to 2.2.0

- README.md
In https://github.com/apache/maven-plugin-tools/commit/5364f90ecedc53193e3b2fe24705025a18af6dce, the repo was updated to reference GitHub issues instead of a JIRA instance - but a reference to `[jira]` was missed and the link is now broken:
Removed reference.
> docs: Remove (non-functional) JIRA `README.md` link
